---
- name: Install and Configure Prometheus
  hosts: all
  become: yes
  vars_files:
    - config.yml

  tasks:

    - name: "Copy Prometheus tarball to host"
      copy:
        src: "/tmp/prometheus-{{ prometheus.version }}.linux-amd64.tar.gz"
        dest: "/tmp/prometheus-{{ prometheus.version }}.tar.gz"
        mode: "0644"
      when: prometheus.enabled

    - name: "Ensure /opt/prometheus directory exists"
      file:
        path: /opt/prometheus
        state: directory
        mode: "0755"
      when: prometheus.enabled

    - name: "Extract Prometheus"
      unarchive:
        src: "/tmp/prometheus-{{ prometheus.version }}.tar.gz"
        dest: "/opt/prometheus/"
        remote_src: yes
        creates: "/opt/prometheus/prometheus-{{ prometheus.version }}.linux-amd64/prometheus"
      when: prometheus.enabled | default(False)

    - name: "Copy Prometheus binaries to /usr/local/bin"
      copy:
        src: "/opt/prometheus/prometheus-{{ prometheus.version }}.linux-amd64/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        mode: "0755"
      loop:
        - prometheus
        - promtool
      when: prometheus.enabled

    - name: "Create Prometheus directories"
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: "0755"
      loop:
        - /etc/prometheus
        - /var/lib/prometheus
      when: prometheus.enabled

    - name: "Copy Prometheus config and consoles"
      copy:
        src: "/opt/prometheus/prometheus-{{ prometheus.version }}.linux-amd64/{{ item }}"
        dest: "/etc/prometheus/{{ item }}"
        mode: "0644"
      loop:
        - prometheus.yml
        - consoles
        - console_libraries
      when: prometheus.enabled

    - name: "Create systemd service for Prometheus"
      copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=root
          ExecStart=/usr/local/bin/prometheus \
            --config.file=/etc/prometheus/prometheus.yml \
            --storage.tsdb.path=/var/lib/prometheus

          [Install]
          WantedBy=multi-user.target
        mode: "0644"
      when: prometheus.enabled

    - name: "Reload systemd"
      systemd:
        daemon_reload: yes
      when: prometheus.enabled

    - name: "Enable and start Prometheus service"
      systemd:
        name: prometheus
        enabled: yes
        state: started
      when: prometheus.enabled and prometheus.start_service
